micronaut:
  application:
    name: renda-fixa-banking
    server:
      port: 8081
  endpoints:
    routes:
      sensitive: false
  netty:
    default:
      allocator:
        max-order: 30
  http:
    client:
      connect-timeout: 10s
      num-of-threads: 200
      pool:
        enabled: true
        max-connections: 200

io:
  netty:
    event-loop-threads: 200