/*
 * API Consulta Renda Fixa
 * Uma API para listar aplicações e produtos Renda Fixa.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package rendafixa.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.micronaut.core.annotation.Introspected;
import io.micronaut.serde.annotation.Serdeable;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.annotation.Generated;
import micronaut.invoker.annotation.HardNullable;

import java.time.LocalDate;
import java.util.Objects;

/**
 * AplicacaoResponse
 */
@Serdeable
@JsonPropertyOrder({
    ConsultaAplicacaoResponse.JSON_PROPERTY_ID,
    ConsultaAplicacaoResponse.JSON_PROPERTY_VALOR,
    ConsultaAplicacaoResponse.JSON_PROPERTY_DATA
})
@Generated(value = "io.micronaut.openapi.generator.JavaMicronautServerCodegen")
@Introspected
public class ConsultaAplicacaoResponse {

    public static final String JSON_PROPERTY_ID = "id";
    public static final String JSON_PROPERTY_VALOR = "valor";
    public static final String JSON_PROPERTY_DATA = "data";

    /**
     * O ID da aplicação.
     */
    @HardNullable
    @Schema(name = "id", description = "O ID da aplicação.", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private Integer id;

    /**
     * O valor da aplicação.
     */
    @HardNullable
    @Schema(name = "valor", description = "O valor da aplicação.", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    @JsonProperty(JSON_PROPERTY_VALOR)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private Double valor;

    /**
     * A data da aplicação.
     */
    @HardNullable
    @Schema(name = "data", description = "A data da aplicação.", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    @JsonProperty(JSON_PROPERTY_DATA)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private LocalDate data;

    public ConsultaAplicacaoResponse() {
    }

    /**
     * O ID da aplicação.
     * @return the id property value
     */
    public Integer getId() {
        return id;
    }

    /**
     * Set the id property value
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Set id in a chainable fashion.
     * @return The same instance of AplicacaoResponse for chaining.
     */
    public ConsultaAplicacaoResponse id(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * O valor da aplicação.
     * @return the valor property value
     */
    public Double getValor() {
        return valor;
    }

    /**
     * Set the valor property value
     */
    public void setValor(Double valor) {
        this.valor = valor;
    }

    /**
     * Set valor in a chainable fashion.
     * @return The same instance of AplicacaoResponse for chaining.
     */
    public ConsultaAplicacaoResponse valor(Double valor) {
        this.valor = valor;
        return this;
    }

    /**
     * A data da aplicação.
     * @return the data property value
     */
    public LocalDate getData() {
        return data;
    }

    /**
     * Set the data property value
     */
    public void setData(LocalDate data) {
        this.data = data;
    }

    /**
     * Set data in a chainable fashion.
     * @return The same instance of AplicacaoResponse for chaining.
     */
    public ConsultaAplicacaoResponse data(LocalDate data) {
        this.data = data;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ConsultaAplicacaoResponse aplicacaoResponse = (ConsultaAplicacaoResponse) o;
        return Objects.equals(this.id, aplicacaoResponse.id) &&
            Objects.equals(this.valor, aplicacaoResponse.valor) &&
            Objects.equals(this.data, aplicacaoResponse.data);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, valor, data);
    }

    @Override
    public String toString() {
        return "AplicacaoResponse("
            + "id: " + getId() + ", "
            + "valor: " + getValor() + ", "
            + "data: " + getData()
            + ")";
    }

}